version: '3.8'
services:
  python_server:
    build:
      context: ./python_server
      dockerfile: Dockerfile
    ports:
      - "${PYTHON_PORT}:3001"
    environment:
      - DATABASE_URL=${POSTGRES_URL}
    volumes:
      - ./python_server:/app
    depends_on:
      - postgres_db
    networks:
      - thequizz-net

  questionary:
    build:
      context: ./questionary
      dockerfile: Dockerfile
    ports:
      - "${QUEST_PORT}:3000"
    volumes:
      - ./questionary:/app
    networks:
      - thequizz-net

  postgres_db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POST_PORT}:5432"
    networks:
      - thequizz-net

networks:
  thequizz-net:
    driver: bridge

volumes:
  postgres_data:
